<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>REST_postPatientDeTesterForHospitalA</name>
   <tag></tag>
   <elementGuidId>76cad613-16f0-4cb4-babb-6022eed2747e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Encoding</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Charset</name>
      <type>Main</type>
      <value>utf-8</value>
   </httpHeaderProperties>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>first_name</name>
      <type>Main</type>
      <value>test</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>last_name</name>
      <type>Main</type>
      <value>de Tester</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bsn</name>
      <type>Main</type>
      <value>123412345</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>birthdate</name>
      <type>Main</type>
      <value>1980-03-07</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gender</name>
      <type>Main</type>
      <value>Man</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>street</name>
      <type>Main</type>
      <value>Ringweg</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zipcode</name>
      <type>Main</type>
      <value>1234AB</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>city</name>
      <type>Main</type>
      <value>Rotterdam</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>phone</name>
      <type>Main</type>
      <value>0101234567</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>email</name>
      <type>Main</type>
      <value>test@detester.com</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>insurance_company</name>
      <type>Main</type>
      <value>NN</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>insurance_number</name>
      <type>Main</type>
      <value>12345678</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hospital</name>
      <type>Main</type>
      <value>A</value>
   </restParameters>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://epdonline.herokuapp.com/api/v1/patients?api_token=salves-epd-46374434340</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
