<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>post</name>
   <tag></tag>
   <elementGuidId>56198330-5503-4163-a6ef-e08883cc2530</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Charset</name>
      <type>Main</type>
      <value>utf-8</value>
   </httpHeaderProperties>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>first_name</name>
      <type>Main</type>
      <value>Tester</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>last_name</name>
      <type>Main</type>
      <value>De Tester</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initials</name>
      <type>Main</type>
      <value>M</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bsn</name>
      <type>Main</type>
      <value>135925090</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>street</name>
      <type>Main</type>
      <value>Ringweg</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>housenumber</name>
      <type>Main</type>
      <value>4</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zipcode</name>
      <type>Main</type>
      <value>1234ac</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>city</name>
      <type>Main</type>
      <value>Rotterdam</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>phone</name>
      <type>Main</type>
      <value>0101234567</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>insurance_company</name>
      <type>Main</type>
      <value>NN</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>insurance_number</name>
      <type>Main</type>
      <value>12345678</value>
   </restParameters>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hospital</name>
      <type>Main</type>
      <value>A</value>
   </restParameters>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://epdonline.herokuapp.com/api/v1/patients?api_token=salves-epd-46374434340</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
